### ISSUE TITLE
com mysql

### ISSUE THREAD

**Issue by Jamsux** [khony/zabbix-bacula#1]
fábio, tudo bem?

Essa é a melhor forma de implementar o monitoramento e é exatamente o q eu preciso. Só q meu banco é MYSQL será q teria condições de dar uma forcinha? não entendo de postgres

**Comment by fabiomello** [comment]
Opa jovem, com certeza! 
Eu só não tinha começado ainda porque minha demanda aqui por mysql é pouca... 
Vou fazer a migração para MySQL e te aviso, acho que esta semana ainda dará tempo 

De: "Jamsux" notifications@github.com 
Para: "khony/zabbix-bacula" zabbix-bacula@noreply.github.com 
Enviadas: Segunda-feira, 10 de outubro de 2016 21:16:28 
Assunto: [khony/zabbix-bacula] com mysql (#1) 

fábio, tudo bem? 

Essa é a melhor forma de implementar o monitoramento e é exatamente o q eu preciso. Só q meu banco é MYSQL será q teria condições de dar uma forcinha? não entendo de postgres

**Comment by Jamsux** [comment]
Fabio,

eu consigo montar um servidor de teste em Nuvem se quiser.
manda uma mensagem: jamsux@gmail.com q te passo as credenciais.

**Comment by fabiomello** [comment]
em testes!

**Comment by victorqone** [comment]
Thank you for program to Mysql

**Comment by victorqone** [comment]
Fabio, tudo bem?
Estou com um problema na execução do script você poderia me ajudar?

ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM Job WHERE name='' ORDER BY jobid DESC LIMIT 1 OFFSET 0' at line 1
